spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            clientId: GhTvseySTJ2hulm37cLj
            client-secret: EYBDWnBmqF
          kakao:
            clientId: 8efb03521a49438939433b729ded52d7
          google:
            clientId: 669565767677-n50906661v9ghf0qgcumgopj4nee0a5f.apps.googleusercontent.com
            client-secret: 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
          facebook:
            clientId: 788636982526228
            client-secret: c43df1ede9fff1d52caeb353ee9fdd9f
          instagram:
            clientId: 1426701191458907
            client-secret: 3865a0979fbb2b03545315a36244b91b